### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models/java14m/saved_model_iter8

### ISSUE THREAD

**Issue by onewhl** [tech-srl/code2vec#1]
Hi! I tried to run code2vec model and faced with problem associated with mistake in README 

I used trained model from https://s3.amazonaws.com/code2vec/model/java14m_model.tar.gz
When I run:
`python3 code2vec.py --load models/java14m/saved_model_iter8 --predict`
I saw this
` Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models/java14m/saved_model_iter8`

The reason is that archive contains model with name "saved_model_iter8.release" 
If we run like below all will be fine
`python3 code2vec.py --load models/java14m/saved_model_iter8.release --predict`

Please fix README or rename model in archive. Thanks

**Comment by urialon** [comment]
Hi Zarina, 
Thanks for letting us know.
I added a note to the README - if you use our trained model add the ".release" suffix when specifying the model's load path.
I don't want to rename the archived file because the file there is in a "released" state, which means it takes 3x less disk space but cannot be further trained.
Please let me know if you find any more mistakes.

**Comment by onewhl** [comment]
@urialon , thank you!
