### ISSUE TITLE
evaluation metric

### ISSUE THREAD

**Issue by Marvinmw** [tech-srl/code2vec#112]
Hi,
I am implementing code2vec in Pytorch.
I feel confused about the evaluation metrics based on subtokens. When recall f1 acc and precision are computed, is only top-1 predicted label used? Or consider top-K, e.g., top-5, to compute evaluation metrics ?

**Comment by urialon** [comment]
Hi @Marvinmw ,

We computed Precision/Recall/F1 only based on the **top-1** predicted label, over subtokens, case insensitive.

Let me know when your implementation is ready, and I will add a link from this repository's README to your repo.

Best,
Uri

**Comment by Marvinmw** [comment]
> Hi @Marvinmw ,
> 
> We computed Precision/Recall/F1 only based on the **top-1** predicted label, over subtokens, case insensitive.
> 
> Let me know when your implementation is ready, and I will add a link from this repository's README to your repo.
> 
> Best,
> Uri

It is still on the way. By the way, for name prediction, what is the frequency threshold to remove the rare method names?

**Comment by urialon** [comment]
Hi @Marvinmw ,
We used a `min_count` threshold initially, and later in the implementation, I switched that to vocabulary size (it's kind of the inverse measure because `min_count` counts the minimal number of occurrences in order to enter the vocabulary, while vocabulary size counts the maximal size of the vocabulary).
So currently in Java, the target vocabulary size is :
`self.MAX_TARGET_VOCAB_SIZE = 261245`

See also:
https://github.com/tech-srl/code2vec/blob/master/config.py#L62

Best,
Uri
