### ISSUE TITLE
How do i build function classifier using code2vec?

### ISSUE THREAD

**Issue by mosh98** [tech-srl/code2vec#123]
Hi,
i would like to build a method/function classifier using code2vec,  the labels are going to be 0,1,2.

Could i get some suggestions on how to build it?

Any guidelines would be hugely appreciated! :D

**Comment by urialon** [comment]
Hi @mosh98 ,
Thank you for your interest in our work!

Yes, this is very easy.
You just need the training+test+validation data to contain the labels 0,1,2 as the first "word", instead of the method name.
The question is where do these 0,1,2 labels come from? If you can know them given the method content, you can modify the `JavaExtractor` to output 0,1,2 instead of the method name. Otherwise, maybe you can add these labels, a-priori, as comments in the `*.java` files, and read them from the `JavaExtractor`?

Then when you run preprocessing, these labels will be automatically indexed and the model will learn to output them.

By the way, I suggest working with our improved model [code2seq](https://code2seq.org/). Even if your output is 0,1,2 rather than a sequence, code2seq's encoder is much better.

Best,
Uri

**Comment by mosh98** [comment]
Hello,

Thank you for the getting back to me :D

We have prepared a dataset containing function and labels along with it.

Thanks for the idea for code2seq, I will look into it.

Best Regards,
Mosh
