### ISSUE TITLE
Getting whole AST like the paper

### ISSUE THREAD

**Issue by zayedupal** [tech-srl/code2vec#13]
Hi,
I am currently working on a research project regarding code similarity. For that, it would be really helpful for us if we could get the whole AST. From the code, I can get different number attention paths, but not the whole tree like the paper. Any guideline for that is really appreciated.

**Comment by urialon** [comment]
Hi Zayed,
The JavaExtractor first parses the code to get the AST, and only then extracts paths.
So instead of extracting paths, you can change the code here:
https://github.com/tech-srl/code2vec/blob/master/JavaExtractor/JPredict/src/main/java/JavaExtractor/FeatureExtractor.java#L40

to print the AST / save it to a file.

**Comment by zayedupal** [comment]
Thank you. That was fast.
