### ISSUE TITLE
JavaExtractor: Potential bug in FeatureExtractor

### ISSUE THREAD

**Issue by clause** [tech-srl/code2vec#15]
In FeatureExtractor line 182, `if (i == 0 || s_ParentTypeToAddChildId.contains(currentNode.getUserData(Common.PropertyKey).getRawType()))` the rawType of _currentNode_ is checked.  In the rest of the code (lines 156 and 167), the rawType of _currentNode.getParentNode()_ is checked.  Is this an intentional difference?  If so why?

**Comment by urialon** [comment]
Hi James,
You are right. This is indeed a bug. Thanks for letting me know!

However, I think that the effect of this bug is very minor. If I fixed it now, it will break the already trained models because the paths at test time will not be exactly as they were at training time.

So - if you are going to train a new model - you can definitely fix it in your version and train a model on the fixed paths. If you take one of our trained models - just keep it as is, the effect is very minor.

**Comment by clause** [comment]
Thanks.  Can you explain the reason for sometimes including the childIDs in the path expression?  I didn't see an explanation in the paper (e.g. Example 3.1 doesn't include them).

**Comment by urialon** [comment]
Yes, sure:
The idea is to help the model to distinguish between children of the same parent, where the order is important.
For example, the children of a `Call`  node (i.e., `myObj.foo()`) are the object and the called method name.
if a path from `myObj` goes to some other node in the AST, we want to let the model know that `myObj` is the first child of `Call` rather than the second child.

So the path will look like: `myObj,[Name0^Call.....],target`
And the path coming from `foo` to `target` will look like: `foo,[Name1^Call.....],target`
This way, hopefully, the model will be more expressive.
So the idea was to add this child id to nodes whom the order matters for their parent nodes, such as:
`myArray[index]`
`myObj.foo()`
`foo(myArg)`

Does it make sense?

**Comment by clause** [comment]
Ok, so `childID`s are included when the child's type isn't enough to distinguish it from it's siblings?  For example, `AssignExpr` has two `Expression` childen (target and value; which can both be leaves) so target and value are distinguished by their childIDs.  If that's the purpose, why are the childID's of the source and target elements in a path always included, even if their type is unique among its siblings?

**Comment by urialon** [comment]
Exactly, but not in all cases. As a heuristic, I added manually only for 4-5 cases, and I think that I didn't include `AssignExpr`. There no special reason... You can try to add more types or add child_id for all but I don't think it will matter that much.
At some point in the research, we figured out that the source and the target nodes are the most important, so as another heuristic I added child_Id for them always. But now I think that it doesn't matter that much as well.
