### ISSUE TITLE
Can I get the exact values for the context

### ISSUE THREAD

**Issue by anonSubmissionGithub** [tech-srl/code2vec#173]
Hi,

Thank you for your great work! While running the model, I get the context like this "context: file,(ClassOrInterfaceType0)^(ClassOrInterfaceType)^(MethodDeclaration)_(NameExpr2),METHOD_NAME".
Can I get the exact values instead (eg. Method name, expression)?

Thank you.
Samiha

**Comment by urialon** [comment]
Hi @anonSubmissionGithub ,

Thank you for your interest in our work!

Can you please explain what exactly were you running, whether you've made any modifications to the code, and if possible, what is the downstream task that you are addressing?

My response may be slow because of the holidays.
I also recommend checking out the newer, general-purpose and multi-language model polyCoder:

https://github.com/VHellendoorn/Code-LMs

Best,
Uri

**Comment by anonSubmissionGithub** [comment]
Hi Dr. Alon, Thank you so much for your quick response during the holidays. I think I figured it out myself. Also, it is exciting to get the link to your new work.
