### ISSUE TITLE
Probability shown for a codeblock in the code2vec.org and after downloading the project are different

### ISSUE THREAD

**Issue by zayedupal** [tech-srl/code2vec#21]
Hi,

I have used the released model you have provided in the repository.
However, if I test it using the same codeblock in code2vec.org and locally, the values are different. I have just followed the instructions provided in the readme to run and predict.
Here's the codeblock to test:
````
void f(int[] list){
    for(int i =1; i<list.length;i++){
        int currentElement = list[i];
        int k;
        for(k =i-1;k>=0&&list[k]>currentElement;k--){
            list[k+1]=list[k];
        }
        list[k+1]=currentElement;
    }

}
````
The probability shown in code2vec site is **insertionSort 82.35%** , **sortByInsertionSort
6.49%**
The probability shown in the git project is **(0.549103) predicted: ['sort', 'by', 'insertion', 'sort']**, **(0.095443) predicted: ['min', 'key']**, **(0.074358) predicted: ['insertion', 'sort']**

Is the model used in the website and provided in the git repository different? Or I am missing something?

Thank you,
Zayed

**Comment by urialon** [comment]
Hi @zayedupal,
Sorry, I somehow missed this issue. 

Yes, the bottom line is that the model at code2vec.org is not the same as in this repository. It was trained using almost the same code and on the same data, the differences are only because these are different training runs and because we fixed some issues since the website lunch.

The reason is that we first used our original model on the code2vec.org website, such that the examples in the paper and the examples on the website will produce the same results. Later, when open sourced the code, we made some refactoring so the code will be easier to read and modify, and fixed a few minor bugs. For this reason, the original model could not be loaded anymore with the new code, so we needed to train the model again to make it available. 

But these two models are almost the same. The model that you can download in this repository is actually *better* than the one on code2vec.org: if you run it on the test set, you'll get about +1 F1 score than the scores that we originally reported in the paper.

Let me know if you have any other questions, I promise to answer more quickly next time.
Best,
Uri
