### ISSUE TITLE
[Request] restore paper-version

### ISSUE THREAD

**Issue by iTakeshi** [tech-srl/code2vec#29]
Hi, thank you for providing the official implementation of you outstanding paper.

I found that you recently removed the `paper-version` branch from the repo. https://github.com/tech-srl/code2vec/commit/1c92dabc12b227e1ab70c0a1c67693bf6f20cf2e
I'd like to investigate your original implementation in detail in comparison with the current `master` branch.
I would be grateful if you could consider to restore the branch.

Thank you.

**Comment by urialon** [comment]
Hi,
The master branch is the paper version. 
Recently, @eladn has made some changes which included updating some of the TensorFlow APIs.
I think that the `paper-version` branch existed because we thought that we needed to separate it, but eventually we merged the master (which was the paper version) with the updated APIs.

Are you specifically interested in anything specific that you have seen in the `paper-version` branch? Otherwise - the master is the paper version (with updated APIs).
If you need the implementation before the updated TF APIs, you can checkout the commit before @eladn 's pull request.

Let me know if there are still any questions.

**Comment by iTakeshi** [comment]
I see, thank you.

Then, I have a question about the size of code vector:
In the paper (specifically, the unnumbered equation at the middle of page 1:11 in the PDF https://arxiv.org/pdf/1803.09473.pdf), the code vector $\tilde c_i$ is defined as $tanh(W \dot c_i)$, where $W \in \Real^{d \times 3d}$. Since $d$ is 128, the final code vector should be 128-dim, but in the code (at both master HEAD and 16e3071 before the PR) indicates the code vector is 3d-dim (384-dim).
Before the PR:
https://github.com/tech-srl/code2vec/blob/1104c6daacc725212f62cdd2e02e04949bed60de/model.py#L301-L303
master HEAD:
https://github.com/tech-srl/code2vec/blob/8fb4c508aeb466e7ae189650057a97dc50b477c6/config.py#L143-L146
My intention for this issue was to see if the code for paper version defines the code vector size as 128-dim or not.

Although I believe this discrepancy between the paper and the implementation makes almost no difference, it might be helpful for readers to avoid confusion if you clearly state about this in README or somewhere else.

**Comment by urialon** [comment]
Hi,
Yes, in the paper, for brevity, we defined it as `d`, and finally got the best results with a model that had `3d`. I don't think that the `3d` is the reason for the slightly better results, it might have been random. I don't think it really matters.

By the way, in the current implementation, as you probably have noticed already, [you can change the code vector size](https://github.com/tech-srl/code2vec/blob/master/config.py#L66) to any size

Thank you for noticing!

**Comment by iTakeshi** [comment]
Got it, thank you for your kind reply!

**Comment by urialon** [comment]
Sure, let us know if you have any question or problem.
