### ISSUE TITLE
Where can i find the word_freq_dict_path

### ISSUE THREAD

**Issue by j0rd1smit** [tech-srl/code2vec#36]
Hi, I tried to run the model using your example. However if I run `python3 code2vec.py --load models/java14_model/saved_model_iter8 --predict` I get the error:

`Loading word frequencies dictionaries from: None ..`

Where can i find `.dict.c2v` file that is needed for `self.config.word_freq_dict_path`?

PS I have already downloaded the weights of the network

**Comment by urialon** [comment]
Hi,
Sorry for this, we recently made a major refactoring and it might have broken.
The model is looking for the file `dictionaries.bin` which is in the same directory as the saved model (i.e., `models/java14_model/dictionaries.bin`).
As an immediate step, you can go back:
```git checkout 9789cfa0d7ee74b8dca9e2b84c45228b86716d1c```

@eladn can you check why does the model cannot find `dictionaries.bin`?

**Comment by eladn** [comment]
Hi.

The problem is with the command-line you used. I guess you downloaded the trainable model. If so, I'm afraid the model load path you specified does not exist. In that case, you should change the load path to `--load models/java14m_trainable/saved_model_iter8` instead of `--load models/java14_model/saved_model_iter8`.

I'll make sure to change the displayed error to a more informative one.

Thanks for letting us know about this issue.
Elad
