### ISSUE TITLE
Problems when Extending to Python

### ISSUE THREAD

**Issue by liangxi11** [tech-srl/code2vec#57]
Hello! I tried to extend the code2vec to Python, but I encountered some problems.
I successfully use [PathMiner](https://github.com/vovak/astminer) to create the preprocess data in a triple components format (Token, Path, Token), but I am not able to run bash train.sh because I still need dataname.dict.c2s.

What is  dataname.dict.c2s? And how can I deal with it?

**Comment by urialon** [comment]
Hi,
Nice work.
You need to run the "preprocess.sh" script, and make it use your code instead of running our JavaExtractor.

As long as your code and the JavaExtractor produce the same format of output, the preprocess.sh script will create the dataset (including the *.dict file).

See also:
https://github.com/tech-srl/code2vec/blob/master/README.md#extending-to-other-languages

Best,
Uri
