### ISSUE TITLE
The file encoding of "dataset.train.c2v"?

### ISSUE THREAD

**Issue by jumormt** [tech-srl/code2vec#64]
I wonder the valid encoding of “dataset.train.c2v”. Editing with `vim`, I found the data are simply lines of specified format path contexts("methodname source,path,target"). To build the dataset, I guess one just needs to write each line following that format. It turns out that when encoding with "utf-8" the padding process went wrong somehow and I get the following error lines:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 19 in record [Op:IteratorGetNextSync]`

It means the dimension of input data does not match the model input, but the padding process had already been done.

**Comment by urialon** [comment]
Hi @jumormt ,
Thank you for your interest in code2vec.

This is correct, you can find more details about the file format here:
https://github.com/tech-srl/code2vec#extending-to-other-languages

To build the dataset, you need to write each line following this format, but then there is additional preprocessing that pads the data to complete/truncate it to 201 fields.
This additional preprocessing starts here: https://github.com/tech-srl/code2vec/blob/master/preprocess.sh#L51
(I don't think it has anything to do with utf-8)

Best,
Uri

**Comment by jumormt** [comment]
Thanks for your answer. Having read the informative python script `path_context_reader.py`, I think this is due to the implementation of `tf.data.experimental.CsvDataset`, which entails using the symbol(`field_delim`) to fill the length of `record_defaults`. 

Does the order of path contexts in each method matter cos `random.sample` is used to sample `max_context` path contexts? If so, what is the predefined order?

**Comment by urialon** [comment]
Hi,
The order does not matter, because if there are more than 200 contexts, they are sampled here:
https://github.com/tech-srl/code2vec/blob/master/preprocess.py#L50

If there are less than 200 contexts, the order still does not matter because the model does not take the order into account (the model treats the contexts as a set).

I recommend to also check out our newer code2seq model at: https://code2seq.org/ .
The source code interface and file format are very similar to code2vec, but its performance is much better.

Best,
Uri

**Comment by jumormt** [comment]
Thanks a lot. Both works are fascinating and worth studying.
