### ISSUE TITLE
Code Representation for code clones

### ISSUE THREAD

**Issue by MaxVortman** [tech-srl/code2vec#9]
Hello and thank you for your job!  
I'm now working in code clones problem and I would like to use your approach for code representation. When I read your paper I wonder I can use your trained model for my problem, but I see nothing about that. How I can use your's model? As I see your output predictions contains only names for methods and attention scores, but I need just a vector of input java code. Is it possible?
Thank you!

**Comment by urialon** [comment]
Hi Max,
Yes! There is a simple way to extract the code vectors of a given example.

First, If you want to get the code vector of a *single* example at a time - use the `--predict` command line flag that allows interactive prediction. Alternatively, if you want to convert a large batch of files to vectors, preprocess those files using the `preprocess.sh` scripts (point the "test_dir" path to your files, the training and validation paths don't matter. Then use your new `test.c2v` file with **our trained model and our dictionary.bin**), and use the `--test` command line flag.
In the function [build_test_graph](https://github.com/tech-srl/code2vec/blob/master/model.py#L329), the variable `code_vectors` holds the batch of code vectors. You just need the function to return this variable as an additional return value.
In the function that calls `build_test_graph` - which is [predict](https://github.com/tech-srl/code2vec/blob/master/model.py#L356) if you're in `--predict` mode and [evaluate](https://github.com/tech-srl/code2vec/blob/master/model.py#L134) if you're in "--test" mode, accept the additional return value. E.g., in evaluate:
Instead of:
```
self.eval_top_words_op, self.eval_top_values_op, self.eval_original_names_op, _, _, _, _ = \
    self.build_test_graph(self.eval_queue.get_filtered_batches())
```
Replace the first line with:
```
self.eval_top_words_op, self.eval_top_values_op, self.eval_original_names_op, _, _, _, _, self.code_vectors_op = \
```
Then, whenever you're calling `self.sess.run` with these return values as arguments (if you're in `--test` mode, it's [here](https://github.com/tech-srl/code2vec/blob/master/model.py#L159)), add the new `self.code_vectors_op` to the list of variables to "run", and add a receiving variable.

Instead of (here):
```
top_words, top_scores, original_names = self.sess.run(
                    [self.eval_top_words_op, self.eval_top_values_op, self.eval_original_names_op],
                    feed_dict={self.eval_placeholder: batch})
```

Use:
```
top_words, top_scores, original_names, code_vectors = self.sess.run(
                    [self.eval_top_words_op, self.eval_top_values_op, self.eval_original_names_op, self.code_vectors_op],
                    feed_dict={self.eval_placeholder: batch})
```

And that's it! the variable "code_vectors" is now a numpy matrix, where each row corresponds to a single Java method. You can write it to a file or pass it somewhere else.

Let me know if it works for you. if not, maybe I'll add it as an additional feature.

**Comment by sci2lab** [comment]
Hi Uri!
Thank you for the great work and research paper. I'd like it very much! I am working on a similar problem, code clone/similarities between code snippets. And I need the vector representation of code snippets. As you mentioned it could be used for a variety of applications. It would be great, if you'd add it as a feature with explanation as I had the same issue of figuring it out, which wasn't that easy.
Thanks,
M.

**Comment by urialon** [comment]
Sure, I'll just add it as an additional feature.
I'm thinking about adding a flag `--export_code_vectors <FILE>` which can be used in either `--test` or `--predict` modes.
In `--test`, it will load a preprocessed test set, and save the vectors to a text file, where each row of the test set will correspond to the vector in the saved text file.
In `--predict`, the user will just manually modify the file `Input.java` as it is now, but the vector will be printed to console in addition to the prediction.

Would these be useful use cases for you?

**Comment by sci2lab** [comment]
That certainly helps. Thank you! 
I am thinking of a more general tool/application similar to word2vec, that can get a code snippet and returns the arbitrary long vector representation of it. It could help researchers dramatically for creating a lot of interesting applications.
Thanks again.
M.

**Comment by MaxVortman** [comment]
Uri, thanks a lot!  
It works. I didn't expect your answer so quickly. 
Thank you!

**Comment by urialon** [comment]
@MaxVortman sure, no problem.
@sci2lab ok, so I'll implement it as an additional flag as I suggested, that can be performed either on a single java snippet or on a large batch of them. I hope this will be general enough that every person can adapt it to his needs.

**Comment by urialon** [comment]
Implemented, see instructions here: [https://github.com/tech-srl/code2vec#exporting-the-code-vectors-for-the-given-code-examples](https://github.com/tech-srl/code2vec#exporting-the-code-vectors-for-the-given-code-examples)

Let me know if there are any problems.
