### ISSUE TITLE
[question] Use of hash on paths contexts

### ISSUE THREAD

**Issue by jeandersonbc** [tech-srl/code2vec#98]
Hi @urialon,

Thanks for making all the great work on Code2Vec available :)
I'm starting to play a bit with it and noticed that the triplets extracted from a method are in the form <token,hash,token>.
I managed to disable the hash option but I was wondering if the hash is just to save space or if that's how Code2Vec actually understands AST paths.

Thanks in advance!
-jean

**Comment by jeandersonbc** [comment]
PS: Just noticed that the latest question at #96 also addresses my question. Looking forward to the clarification :)

**Comment by urialon** [comment]
Hi @jeandersonbc ,
Thank you for your interest in code2vec!

In code2vec, the hash is just to save space, because the entire path is treated as a single symbol.
In [**code2seq**](https://code2seq.org/), we do not hash, because the model reads the path as a sequence of AST paths.

I hope it helps.
Uri

**Comment by jeandersonbc** [comment]
Thank you very much for the clarifications @urialon 
I'm gonna take a look at code2seq in more detail, perhaps that fits best to my use case.
Feel free to close the issue!

Best, Jean

**Comment by urialon** [comment]
Great,
Let me know if you have any further questions!
Uri
